// module.exports.MONGO_LOCAL = 'mongodb://localhost:27017/loftsystem';
module.exports.MONGO_LOCAL = 'mongodb+srv://karmabot:4C3uFAEhoa6W9wkC@cluster0-y78lp.mongodb.net/test?retryWrites=true&w=majority';
module.exports.SESSION_SECRET = 'bvdzfczbuwp8vvcx';
module.exports.SESSION_KEY = 'asfcasf67gfg45wpdfghy';
module.exports.TOKEN_SECRET = 'yZhtj2ayrXXHHKNe';
module.exports.REFRESH_TOKEN_SECRET = 'Vr8d7sa95VESAtwC';
module.exports.PORT = 3000;
module.exports.TOKEN_LIFE = 3600;
module.exports.REFRESH_TOKEN_LIFE = 7200;
module.exports.UPLOAD = './build/assets/img';